media:
  input: src/assets/medias
  output: /src/assets/medias

content:
  - name: pages
    label: Pages
    path: /src/pages
    type: collection
  - name: info_general
    label: General Information
    path: /src/content/data/infoGeneral.json
    type: data
