media:
  input: src/assets/medias
  output: /src/assets/medias

content:
  - name: pages
    label: Pages
    path: /src/pages
    type: collection
    fields:
      - name: title
        label: Title
        type: text
      - content: true
        label: Content
        type: rich-text
