media:
  input: src/assets/medias
  output: /src/assets/medias

content:
  - name: pages
    label: Pages
    type: collection
    path: src/pages
    filename: '{primary}.md'
    view:
      fields: [title, order]
      primary: title
      sort: [order, title]
      default:
        sort: order
        order: asc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }
