# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Association Fleurs & Jardins
edition: 25
date: ANNULATION SUITE CORONAVIRUS 25 et 26 avril 2020
emails:
  contact: salonfleursetjardins@levaudreuil.fr
  presse: marc-alvarez@bbox.fr
phone:
  contact: 02 32 61 27 85
  presse: 02 32 59 14 48
adresse: Rue B. Chedeville – 27100 Le Vaudreuil (27)

description: > # this means to ignore newlines until "baseurl:"
    Le Salon Fleurs et Jardins organisé en plein air sur un site environnemental exceptionnel,
    les bords de l'Eure, est le rendez-vous printanier des amoureux des fleurs et des plantes.
    Il s'adresse aussi bien aux néophytes qu'aux collectionneurs à la recherche des espèces les plus rares.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
relative_permalinks: false

# Google Analytics tracking code
google_analytics: UA-112422626-1

# Social network
facebook_username: levaudreuil.fr
# twitter_username:
# github_username:

header_pages:
  - _pages/02_le-salon.md
  - _pages/02_exposants.md
  - _pages/03_infos-pratiques.md

# Si `footer_page`n'est pas spécifié, une liste de liens de toutes les pages seras affichée.
footer_pages:
  - _pages/01_index.md
  - _pages/04_medias.md
  - _pages/03_infos-pratiques.md
  - _pages/05_mentions-legales.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  pages:
    output: true
    permalink: /:path
  animations:
    output: true
    layout: page
  pages-sections:

defaults:
  - scope:
      path: ""
      type: animations
    values:
      layout: page

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
